"""
Build consolidated One Community Global EN document from extracted page text.
"""
import os
import re
from pathlib import Path
from datetime import datetime

SRC_DIR = Path(r"C:\Users\Isaacko0\HSCSG_v15_OS\_scratch\extracted_en")
OUT_DIR = Path(r"C:\Users\Isaacko0\HSCSG_v15_OS\_scratch")
OUT_DIR.mkdir(exist_ok=True)

# Order matters: start with overview/intro pages
PRIORITY = [
    "overview",
    "what-is-it",
    "who-we-are",
    "purpose-mission-values",
    "methodology",
    "for-the-highest-good-of-all",
    "global-sustainability-strategy",
    "first-five-years",
    "fulfilled-living",
    "highest-good-housing",
    "duplicable-city-center",
    "earthbag-village",
    "highest-good-energy",
    "highest-good-food",
    "highest-good-education",
    "highest-good-economics",
    "highest-good-society",
    "open-source",
    "solutions-that-create-solutions",
    "how-it-happens-2",
    "executive-summary",
    "helping",
    "one-community-pledge",
    "team",
    "one-community-blog",
    "site-map",
    "watch-one-community-overview-video",
    "join-one-community",
    "contribute-join-partner",
    "contact",
    "subscribe",
    "terms-and-conditions",
]

def clean(text):
    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

files = list(SRC_DIR.glob("*.md"))
by_stem = {f.stem: f for f in files}

ordered = []
seen = set()
for name in PRIORITY:
    if name in by_stem:
        ordered.append((name, by_stem[name]))
        seen.add(name)

# Append remaining
for f in sorted(files):
    if f.stem not in seen:
        ordered.append((f.stem, f))

parts = []
parts.append("# One Community Global — Complete Open Source Sustainable Living Blueprints")
parts.append("")
parts.append("**Source:** https://onecommunityglobal.org/")
parts.append(f"**Scraped:** {datetime.now().strftime('%Y-%m-%d')}")
parts.append("**Pages extracted:** 33 structural pages (full site main content)")
parts.append("**License:** Creative Commons BY 3.0 (per site footer)")
parts.append("**Generated by:** HSCSG v15 OS / Hermes Agent (web-extraction-archiver pattern)")
parts.append("")
parts.append("---")
parts.append("")
parts.append("## Table of Contents")
parts.append("")

toc_lines = []
for i, (name, _) in enumerate(ordered, 1):
    display = name.replace("-", " ").title()
    toc_lines.append(f"{i}. **{display}** — `onecommunityglobal.org/{name}/`")
parts.extend(toc_lines)
parts.append("")
parts.append("---")
parts.append("")

for i, (name, fp) in enumerate(ordered, 1):
    display = name.replace("-", " ").title()
    parts.append(f"## {i}. {display}")
    parts.append("")
    parts.append(f"**URL:** https://onecommunityglobal.org/{name}/")
    parts.append("")
    parts.append("---")
    parts.append("")
    text = clean(fp.read_text(encoding="utf-8", errors="ignore"))
    parts.append(text)
    parts.append("")
    parts.append("---")
    parts.append("")

content = "\n".join(parts)
out = OUT_DIR / "ONECOMMUNITY_GLOBAL_COMPLETE_EN.md"
out.write_text(content, encoding="utf-8")
print(f"OK {out} → {len(content)} chars / ~{len(content)//4} tokens / {len(content)/1024:.1f} KB")
