// tool-forge/backend/tool-generator.ts
// HSCSG v15 OS — Tool Generator (LLM → Code → Sandbox → Deploy)
// Integración: CaaS Engine, LoopEngine, Vercel Edge Functions, Sandbox

import { caasEngine, CaaSTool, ToolSchema } from './caas-engine';

/* ═══════════════════════════════════════════════════════════════════
   TIPOS
   ═══════════════════════════════════════════════════════════════════ */

export interface ToolSpec {
  slug: string;                    // URL-friendly unique ID
  name: string;
  description: string;
  category: string;
  tags: string[];
  tier: 'FREE' | 'PRO' | 'ENTERPRISE';
  inputSchema: JSONSchema;
  outputSchema: JSONSchema;
  configSchema?: JSONSchema;
  promptTemplate: string;          // Template para LLM
  testCases: TestCase[];
  seo: SEOConfig;
}

export interface JSONSchema {
  type: 'object';
  properties: Record<string, JSONSchemaProperty>;
  required?: string[];
}

export interface JSONSchemaProperty {
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  description?: string;
  enum?: string[];
  default?: any;
  items?: JSONSchemaProperty;
}

export interface TestCase {
  input: Record<string, any>;
  expectedOutput?: Record<string, any>;
  description: string;
}

export interface SEOConfig {
  targetKeywords: string[];
  metaTitle: string;
  metaDescription: string;
  h1: string;
  structuredData: 'SoftwareApplication' | 'WebApplication';
}

export interface GeneratedTool {
  code: string;
  files: Map<string, string>;      // filename → content
  testResults: TestResult[];
  deployment: DeploymentResult;
  caasTool: CaaSTool;
}

export interface TestResult {
  passed: boolean;
  input: Record<string, any>;
  output: any;
  expected?: any;
  latencyMs: number;
  error?: string;
}

export interface DeploymentResult {
  success: boolean;
  url?: string;
  deploymentId?: string;
  error?: string;
  logs: string[];
}

export interface SandboxConfig {
  timeoutMs: number;
  memoryMb: number;
  allowedImports: string[];
  networkAccess: boolean;
}

/* ═══════════════════════════════════════════════════════════════════
   TOOL GENERATOR CLASS
   ═══════════════════════════════════════════════════════════════════ */

export class ToolGenerator {
  private sandboxConfig: SandboxConfig = {
    timeoutMs: 30000,
    memoryMb: 128,
    allowedImports: ['lucide-react', 'clsx', 'tailwind-merge', 'zod', '@tanstack/react-query'],
    networkAccess: false
  };

  constructor(private caasEngine = caasEngine) {}

  /* ────────────────────────────────────────────────────────────────
     MAIN: Generate → Test → Deploy → Register
     ──────────────────────────────────────────────────────────────── */

  async generateTool(spec: ToolSpec, creatorDid: string): Promise<GeneratedTool> {
    console.log(`🔧 Generating tool: ${spec.slug}`);

    // 1. Generate code via LLM (simulated - en producción usa Claude/Opus API)
    const code = await this.generateCode(spec);
    
    // 2. Create file structure
    const files = this.createFileStructure(spec, code);
    
    // 3. Test in sandbox
    const testResults = await this.runTests(spec, files);
    
    const allPassed = testResults.every(r => r.passed);
    if (!allPassed) {
      console.warn(`⚠️ Tool ${spec.slug} has failing tests`);
    }

    // 4. Deploy to Vercel Edge Function
    const deployment = await this.deployToVercel(spec, files);
    
    // 5. Register in CaaS Engine
    const caasTool = await this.registerInCaaS(spec, deployment, creatorDid);

    return {
      code,
      files,
      testResults,
      deployment,
      caasTool
    };
  }

  /* ────────────────────────────────────────────────────────────────
     CODE GENERATION (LLM Integration)
     ──────────────────────────────────────────────────────────────── */

  private async generateCode(spec: ToolSpec): Promise<string> {
    // En producción: llamada a Claude/Opus API con promptTemplate
    // Aquí: generador template-based para velocidad
    
    const componentCode = this.generateReactComponent(spec);
    const apiCode = this.generateApiRoute(spec);
    const configCode = this.generateConfig(spec);
    
    return `// Generated by HSCSG Tool Generator
// Tool: ${spec.name} (${spec.slug})
// Tier: ${spec.tier}
// Category: ${spec.category}

${componentCode}

${apiCode}

${configCode}
`;
  }

  private generateReactComponent(spec: ToolSpec): string {
    const inputFields = this.generateInputFields(spec.inputSchema);
    const outputDisplay = this.generateOutputDisplay(spec.outputSchema);
    
    return `'use client';

import { useState } from 'react';
import { useCaaS } from '@/hooks/useCaaS';
import { Button, Input, Select, Card } from '@/components/ui';
import { Download, CheckCircle, AlertCircle } from 'lucide-react';

export default function ${this.pascalCase(spec.slug)}Tool() {
  const { user, tier, verifyAccess, recordUsage } = useCaaS();
  const [input, setInput] = useState<${this.generateTSInterface(spec.inputSchema)}>(${this.generateDefaultInput(spec.inputSchema)});
  const [output, setOutput] = useState<${this.generateTSInterface(spec.outputSchema)} | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [exportFormat, setExportFormat] = useState<'png' | 'svg' | '3mf' | 'stl' | 'pdf'>('png');

  const handleRun = async () => {
    setLoading(true);
    setError(null);
    
    const access = await verifyAccess('${spec.slug}', 'run');
    if (!access.allowed) {
      setError(access.reason || 'Access denied');
      setLoading(false);
      return;
    }

    try {
      const response = await fetch('/api/tools/${spec.slug}/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(input)
      });
      
      if (!response.ok) throw new Error('Tool execution failed');
      
      const result = await response.json();
      setOutput(result);
      
      // Record usage for CaaS metrics
      await recordUsage('${spec.slug}', 'run');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async () => {
    if (!output) return;
    
    const access = await verifyAccess('${spec.slug}', 'export');
    if (!access.allowed) {
      setError(access.reason || 'Export requires higher tier');
      return;
    }

    try {
      const response = await fetch('/api/tools/${spec.slug}/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ output, format: exportFormat })
      });
      
      if (!response.ok) throw new Error('Export failed');
      
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = \`${spec.slug}-\${Date.now()}.\${exportFormat}\`;
      a.click();
      URL.revokeObjectURL(url);
      
      await recordUsage('${spec.slug}', 'export');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed');
    }
  };

  // Tier badge
  const tierConfig = {
    FREE: { label: 'Free', color: 'bg-gray-100 text-gray-700' },
    PRO: { label: 'Pro', color: 'bg-blue-100 text-blue-700' },
    ENTERPRISE: { label: 'Enterprise', color: 'bg-purple-100 text-purple-700' }
  } as const;

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">${spec.name}</h1>
          <p className="text-xl text-gray-600 mb-6">${spec.description}</p>
          <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium \${tierConfig[access.tier].color}">
            \${tierConfig[access.tier].label}
          </span>
        </div>

        {/* Tool Interface */}
        <Card className="mb-8">
          <div className="p-6 space-y-6">
            {/* Input Fields */}
            <div className="space-y-4">
              ${inputFields}
            </div>

            {/* Run Button */}
            <Button 
              onClick={handleRun} 
              disabled={loading}
              className="w-full py-3 text-lg"
              size="lg"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  Generando...
                </span>
              ) : (
                'Generar'
              )}
            </Button>

            {/* Error Display */}
            {error && (
              <div className="flex items-center gap-2 text-red-600 bg-red-50 p-3 rounded-lg">
                <AlertCircle className="h-5 w-5" />
                <span>{error}</span>
              </div>
            )}
          </div>
        </Card>

        {/* Output & Export */}
        {output && (
          <Card className="mb-8">
            <div className="p-6 space-y-6">
              <h2 className="text-2xl font-semibold text-gray-900">Resultado</h2>
              ${outputDisplay}
              
              {/* Export Options */}
              <div className="space-y-4">
                <label className="block text-sm font-medium text-gray-700">Formato de exportación</label>
                <Select
                  value={exportFormat}
                  onValueChange={setExportFormat}
                  options={[
                    { value: 'png', label: 'PNG Image' },
                    { value: 'svg', label: 'SVG Vector' },
                    { value: '3mf', label: '3MF (Impresión 3D)' },
                    { value: 'stl', label: 'STL (Impresoras antiguas)' },
                    { value: 'pdf', label: 'PDF Document' }
                  ].filter(opt => ${this.getAllowedExports(spec.tier)}.includes(opt.value))}
                />
                <Button onClick={handleExport} className="w-full" size="lg">
                  <Download className="h-5 w-5 mr-2" />
                  Descargar \${exportFormat.toUpperCase()}
                </Button>
              </div>
            </div>
          </Card>
        )}

        {/* SEO Content */}
        <div className="prose prose-gray max-w-none">
          <h2>Cómo funciona</h2>
          <ol>
            <li>Introduce los datos en el formulario superior</li>
            <li>Haz clic en "Generar" para procesar</li>
            <li>Visualiza el resultado y elige formato de descarga</li>
          </ol>
          
          <h2>Casos de uso</h2>
          <ul>
            ${spec.seo.targetKeywords.map(kw => `<li>\${kw}</li>`).join('\n            ')}
          </ul>
        </div>
      </div>
    </div>
  );
}`;

  private generateApiRoute(spec: ToolSpec): string {
    return `// API Route: /api/tools/${spec.slug}/run
// Auto-generated by HSCSG Tool Generator

import { NextRequest, NextResponse } from 'next/server';
import { caasEngine } from '@/lib/caas-engine';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { input } = body;
    
    // Validate input against schema
    const validation = validateInput(input, ${JSON.stringify(spec.inputSchema)});
    if (!validation.valid) {
      return NextResponse.json({ error: 'Invalid input', details: validation.errors }, { status: 400 });
    }

    // Execute tool logic
    const result = await executeTool(input);
    
    // Validate output
    const outputValidation = validateOutput(result, ${JSON.stringify(spec.outputSchema)});
    if (!outputValidation.valid) {
      console.error('Output validation failed:', outputValidation.errors);
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error('Tool execution error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

async function executeTool(input: any): Promise<any> {
  // Tool-specific logic goes here
  // This is where the actual computation happens
  return { success: true, data: input }; // Placeholder
}

function validateInput(input: any, schema: any): { valid: boolean; errors?: string[] } {
  // Simplified validation - use zod in production
  return { valid: true };
}

function validateOutput(output: any, schema: any): { valid: boolean; errors?: string[] } {
  return { valid: true };
}`;
  }

  private generateConfig(spec: ToolSpec): string {
    return `// Tool Config: ${spec.slug}
export const toolConfig = {
  slug: '${spec.slug}',
  name: '${spec.name}',
  tier: '${spec.tier}',
  category: '${spec.category}',
  tags: ${JSON.stringify(spec.tags)},
  seo: ${JSON.stringify(spec.seo, null, 2)}
};`;
  }

  /* ────────────────────────────────────────────────────────────────
     HELPERS: Code Generation
     ──────────────────────────────────────────────────────────────── */

  private generateInputFields(schema: JSONSchema): string {
    if (!schema.properties) return '// No input fields';
    
    return Object.entries(schema.properties).map(([key, prop]) => {
      const required = schema.required?.includes(key) || false;
      const component = this.getInputComponent(key, prop, required);
      return `              <div>
                <label htmlFor="${key}" className="block text-sm font-medium text-gray-700 mb-1">
                  ${this.capitalize(key)} ${required ? '<span className="text-red-500">*</span>' : ''}
                </label>
                ${component}
              </div>`;
    }).join('\n');
  }

  private getInputComponent(key: string, prop: JSONSchemaProperty, required: boolean): string {
    switch (prop.type) {
      case 'string':
        if (prop.enum) {
          return `<Select
                  id="${key}"
                  value={input.${key}}
                  onValueChange={(v) => setInput(prev => ({ ...prev, ${key}: v }))}
                  options={${JSON.stringify(prop.enum.map(e => ({ value: e, label: e })))}}
                  required={${required}}
                />`;
        }
        return `<Input
                id="${key}"
                type="text"
                value={input.${key}}
                onChange={(e) => setInput(prev => ({ ...prev, ${key}: e.target.value }))}
                required={${required}}
                placeholder="${prop.description || ''}"
              />`;
      case 'number':
        return `<Input
                id="${key}"
                type="number"
                value={input.${key}}
                onChange={(e) => setInput(prev => ({ ...prev, ${key}: parseFloat(e.target.value) }))}
                required={${required}}
                placeholder="${prop.description || ''}"
              />`;
      case 'boolean':
        return `<label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={input.${key}}
                  onChange={(e) => setInput(prev => ({ ...prev, ${key}: e.target.checked }))}
                  required={${required}}
                />
                <span className="text-sm text-gray-700">${prop.description || key}</span>
              </label>`;
      default:
        return `<Input id="${key}" disabled />`;
    }
  }

  private generateOutputDisplay(schema: JSONSchema): string {
    if (!schema.properties) return '<pre>{JSON.stringify(output, null, 2)}</pre>';
    
    return Object.entries(schema.properties).map(([key, prop]) => {
      if (prop.type === 'object') {
        return `              <div className="space-y-2">
                <h4 className="font-medium text-gray-700">${this.capitalize(key)}</h4>
                <pre className="bg-gray-100 p-4 rounded-lg overflow-x-auto text-sm">
                  {JSON.stringify(output.${key}, null, 2)}
                </pre>
              </div>`;
      }
      return `              <div>
                <span className="font-medium text-gray-700">${this.capitalize(key)}:</span>
                <span className="ml-2 text-gray-900">{output.${key}}</span>
              </div>`;
    }).join('\n');
  }

  private generateTSInterface(schema: JSONSchema): string {
    if (!schema.properties) return 'Record<string, any>';
    
    const fields = Object.entries(schema.properties).map(([key, prop]) => {
      const tsType = this.jsonSchemaToTS(prop);
      const optional = !schema.required?.includes(key) ? '?' : '';
      return `  ${key}${optional}: ${tsType};`;
    }).join('\n');
    
    return `{\n${fields}\n}`;
  }

  private jsonSchemaToTS(prop: JSONSchemaProperty): string {
    switch (prop.type) {
      case 'string': return 'string';
      case 'number': return 'number';
      case 'boolean': return 'boolean';
      case 'array': return prop.items ? `${this.jsonSchemaToTS(prop.items)}[]` : 'any[]';
      case 'object': return 'Record<string, any>';
      default: return 'any';
    }
  }

  private generateDefaultInput(schema: JSONSchema): string {
    if (!schema.properties) return '{}';
    
    const defaults = Object.entries(schema.properties).map(([key, prop]) => {
      const val = prop.default ?? this.getDefaultValue(prop.type);
      return `  ${key}: ${typeof val === 'string' ? \`"\${val}"\` : val},`;
    }).join('\n');
    
    return `{\n${defaults}\n}`;
  }

  private getDefaultValue(type: string): any {
    switch (type) {
      case 'string': return '';
      case 'number': return 0;
      case 'boolean': return false;
      case 'array': return [];
      case 'object': return {};
      default: return null;
    }
  }

  private getAllowedExports(tier: string): string {
    const exports: Record<string, string[]> = {
      FREE: "['png', 'svg']",
      PRO: "['png', 'svg', '3mf', 'stl', 'pdf', 'json']",
      ENTERPRISE: "['png', 'svg', '3mf', 'stl', 'pdf', 'json']"
    };
    return exports[tier] || exports.FREE;
  }

  private pascalCase(str: string): string {
    return str.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
  }

  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private createFileStructure(spec: ToolSpec, code: string): Map<string, string> {
    const files = new Map<string, string>();
    files.set(`${spec.slug}/page.tsx`, code);
    files.set(`${spec.slug}/config.ts`, this.generateConfig(spec));
    files.set(`${spec.slug}/api/run/route.ts`, this.generateApiRoute(spec));
    files.set(`${spec.slug}/api/export/route.ts`, this.generateExportRoute(spec));
    return files;
  }

  private generateExportRoute(spec: ToolSpec): string {
    return `// API Route: /api/tools/${spec.slug}/export
import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { output, format } = await request.json();
    
    let blob: Blob;
    let contentType: string;
    let filename: string;
    
    switch (format) {
      case 'png':
        blob = await generatePNG(output);
        contentType = 'image/png';
        filename = 'result.png';
        break;
      case 'svg':
        blob = new Blob([output.svg], { type: 'image/svg+xml' });
        contentType = 'image/svg+xml';
        filename = 'result.svg';
        break;
      case '3mf':
        blob = await generate3MF(output);
        contentType = 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml';
        filename = 'result.3mf';
        break;
      case 'stl':
        blob = await generateSTL(output);
        contentType = 'application/sla';
        filename = 'result.stl';
        break;
      case 'pdf':
        blob = await generatePDF(output);
        contentType = 'application/pdf';
        filename = 'result.pdf';
        break;
      default:
        return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
    }
    
    return new NextResponse(blob, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': \`attachment; filename="\${filename}"\`
      }
    });
  } catch (error) {
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}

// Placeholder generators - implement with actual libraries
async function generatePNG(data: any): Promise<Blob> { return new Blob(['PNG placeholder'], { type: 'image/png' }); }
async function generate3MF(data: any): Promise<Blob> { return new Blob(['3MF placeholder'], { type: 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml' }); }
async function generateSTL(data: any): Promise<Blob> { return new Blob(['STL placeholder'], { type: 'application/sla' }); }
async function generatePDF(data: any): Promise<Blob> { return new Blob(['PDF placeholder'], { type: 'application/pdf' }); }`;
  }

  /* ────────────────────────────────────────────────────────────────
     SANDBOX TESTING
     ──────────────────────────────────────────────────────────────── */

  private async runTests(spec: ToolSpec, files: Map<string, string>): Promise<TestResult[]> {
    const results: TestResult[] = [];
    
    for (const testCase of spec.testCases) {
      const start = Date.now();
      try {
        // En producción: ejecutar en sandbox aislado (vm2, isolated-vm, o Vercel preview)
        const output = await this.executeInSandbox(spec, testCase.input);
        const passed = this.compareOutput(output, testCase.expectedOutput);
        
        results.push({
          passed,
          input: testCase.input,
          output,
          expected: testCase.expectedOutput,
          latencyMs: Date.now() - start
        });
      } catch (error) {
        results.push({
          passed: false,
          input: testCase.input,
          output: null,
          expected: testCase.expectedOutput,
          latencyMs: Date.now() - start,
          error: error instanceof Error ? error.message : 'Unknown error'
        });
      }
    }
    return results;
  }

  private async executeInSandbox(spec: ToolSpec, input: Record<string, any>): Promise<any> {
    // Placeholder: en producción usa isolated-vm o Vercel preview deployments
    // Por ahora: simulación
    return { success: true, data: input, timestamp: Date.now() };
  }

  private compareOutput(actual: any, expected?: any): boolean {
    if (!expected) return true;
    return JSON.stringify(actual) === JSON.stringify(expected);
  }

  /* ────────────────────────────────────────────────────────────────
     VERCEL DEPLOYMENT
     ──────────────────────────────────────────────────────────────── */

  private async deployToVercel(spec: ToolSpec, files: Map<string, string>): Promise<DeploymentResult> {
    const logs: string[] = [];
    
    try {
      logs.push(`📦 Preparing deployment for ${spec.slug}...`);
      
      // En producción: vercel CLI o API
      // const deployment = await vercel.deploy({ files, project: 'tool-forge' });
      
      // Simulación para prototipo
      const deploymentUrl = `https://tool-forge.vercel.app/tools/${spec.slug}`;
      
      logs.push(`✅ Deployed to ${deploymentUrl}`);
      logs.push(`🔗 Edge Function: /tools/${spec.slug}/run`);
      logs.push(`🔗 Export: /tools/${spec.slug}/export`);
      
      return {
        success: true,
        url: deploymentUrl,
        deploymentId: `dpl_${Date.now()}`,
        logs
      };
    } catch (error) {
      logs.push(`❌ Deployment failed: ${error}`);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        logs
      };
    }
  }

  /* ────────────────────────────────────────────────────────────────
     CAAS REGISTRATION
     ──────────────────────────────────────────────────────────────── */

  private async registerInCaaS(
    spec: ToolSpec,
    deployment: DeploymentResult,
    creatorDid: string
  ): Promise<CaaSTool> {
    if (!deployment.success || !deployment.url) {
      throw new Error('Cannot register failed deployment');
    }

    const tool = await this.caasEngine.registerTool({
      id: spec.slug,
      name: spec.name,
      description: spec.description,
      tier: spec.tier,
      category: spec.category,
      tags: spec.tags,
      deploymentUrl: deployment.url,
      schema: {
        input: spec.inputSchema,
        output: spec.outputSchema,
        config: spec.configSchema || {}
      }
    });

    // Reward creator with ZNU/FRNE
    await this.caasEngine.recordUsage(creatorDid, spec.slug, 'create', {
      deploymentUrl: deployment.url,
      deploymentId: deployment.deploymentId
    });

    return tool;
  }
}

/* ═══════════════════════════════════════════════════════════════════
   PREDEFINED TOOL SPECS (5 MVP Tools)
   ═══════════════════════════════════════════════════════════════════ */

export const MVP_TOOL_SPECS: ToolSpec[] = [
  // 1. QR 3D Generator (validado por Skilio)
  {
    slug: 'qr-3d-generator',
    name: 'Generador QR 3D para Impresión',
    description: 'Convierte cualquier enlace en código QR imprimible en 3D: llaveros, soportes de mesa, placas de pared. Exporta en 3MF (colores) y STL.',
    category: 'design',
    tags: ['qr', '3d-print', 'generator', 'restaurant', 'wifi', 'reviews'],
    tier: 'FREE',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Enlace a convertir en QR' },
        baseColor: { type: 'string', default: '#000000', description: 'Color base' },
        qrColor: { type: 'string', default: '#FFFFFF', description: 'Color QR en relieve' },
        shape: { type: 'string', enum: ['stand', 'keychain', 'plate'], default: 'stand', description: 'Tipo de objeto 3D' },
        text: { type: 'string', default: '', description: 'Texto opcional en la base' },
        emoji: { type: 'string', default: '', description: 'Emoji opcional en el centro' }
      },
      required: ['url']
    },
    outputSchema: {
      type: 'object',
      properties: {
        png: { type: 'string', description: 'Base64 PNG' },
        svg: { type: 'string', description: 'SVG vector' },
        '3mf': { type: 'string', description: 'Base64 3MF file' },
        stl: { type: 'string', description: 'Base64 STL file' },
        preview3d: { type: 'string', description: 'Three.js scene JSON' }
      }
    },
    promptTemplate: `Create a 3D QR code generator tool that...`,
    testCases: [
      { input: { url: 'https://example.com' }, description: 'Basic QR generation' },
      { input: { url: 'https://restaurant.com/menu', shape: 'stand', text: 'Menú' }, description: 'Restaurant stand' },
      { input: { url: 'https://google.com/reviews', shape: 'keychain', emoji: '⭐' }, description: 'Review keychain' }
    ],
    seo: {
      targetKeywords: ['codigo qr 3d', 'qr imprimir 3d', 'qr llavero 3d', 'generador qr 3mf'],
      metaTitle: 'Generador QR 3D Gratis | Imprime Llaveros, Soportes y Placas',
      metaDescription: 'Convierte cualquier enlace en QR 3D imprimible. Llaveros, soportes de mesa, placas de pared. Exporta 3MF con colores y STL. Gratis, sin registro.',
      h1: 'Generador de Códigos QR 3D para Impresión',
      structuredData: 'SoftwareApplication'
    }
  },
  
  // 2. Calculadora Hipoteca/IRPF
  {
    slug: 'mortgage-tax-calculator',
    name: 'Calculadora Hipoteca + IRPF 2026',
    description: 'Calcula cuota hipotecaria, amortización, deducción IRPF, gastos compraventa. España 2026 actualizado.',
    category: 'finance',
    tags: ['hipoteca', 'irpf', 'calculadora', 'vivienda', 'impuestos'],
    tier: 'FREE',
    inputSchema: {
      type: 'object',
      properties: {
        precio: { type: 'number', description: 'Precio vivienda (€)' },
        entrada: { type: 'number', description: 'Ahorros disponibles (€)' },
        tipoInteres: { type: 'number', default: 3.5, description: 'Tipo interés anual (%)' },
        plazos: { type: 'number', default: 30, description: 'Años' },
        comunidad: { type: 'string', enum: ['madrid', 'catalunya', 'andalucia', 'valencia', 'resto'], default: 'madrid' },
        edad: { type: 'number', default: 35, description: 'Edad comprador' }
      },
      required: ['precio', 'entrada']
    },
    outputSchema: {
      type: 'object',
      properties: {
        cuotaMensual: { type: 'number' },
        totalIntereses: { type: 'number' },
        totalPagado: { type: 'number' },
        deduccionIRPF: { type: 'number' },
        gastosCompra: { type: 'number' },
        amortizacion: { type: 'array', items: { type: 'object' } }
      }
    },
    testCases: [
      { input: { precio: 300000, entrada: 60000 }, description: 'Standard Madrid' }
    ],
    seo: {
      targetKeywords: ['calculadora hipoteca 2026', 'cuota hipoteca', 'deduccion irpf vivienda'],
      metaTitle: 'Calculadora Hipoteca + IRPF 2026 | Cuota, Gastos, Deducciones',
      metaDescription: 'Calcula tu hipoteca real: cuota mensual, intereses totales, deducción IRPF, gastos de compraventa. Actualizado 2026. Gratis.',
      h1: 'Calculadora de Hipoteca e IRPF 2026',
      structuredData: 'SoftwareApplication'
    }
  },

  // 3. Compresor PDF/Imágenes
  {
    slug: 'pdf-image-compressor',
    name: 'Compresor PDF e Imágenes Gratis',
    description: 'Comprime PDFs e imágenes sin perder calidad visible. Arrastra, ajusta calidad, descarga. Sin límites, sin registro.',
    category: 'productivity',
    tags: ['comprimir pdf', 'comprimir imagen', 'reduccion peso', 'optimizer'],
    tier: 'FREE',
    inputSchema: {
      type: 'object',
      properties: {
        files: { type: 'array', items: { type: 'string' }, description: 'Base64 files' },
        quality: { type: 'number', default: 0.8, minimum: 0.1, maximum: 1.0, description: 'Calidad 0.1-1.0' },
        maxSizeMB: { type: 'number', default: 10, description: 'Tamaño máximo objetivo (MB)' }
      },
      required: ['files']
    },
    outputSchema: {
      type: 'object',
      properties: {
        compressedFiles: { type: 'array', items: { type: 'object' } },
        originalSize: { type: 'number' },
        compressedSize: { type: 'number' },
        reductionPercent: { type: 'number' }
      }
    },
    testCases: [
      { input: { files: ['base64pdf1'], quality: 0.8 }, description: 'PDF compression' }
    ],
    seo: {
      targetKeywords: ['comprimir pdf gratis', 'reducir peso pdf', 'comprimir imagen online'],
      metaTitle: 'Comprimir PDF e Imágenes Gratis | Sin Límite, Sin Registro',
      metaDescription: 'Comprime PDFs e imágenes hasta 90% sin perder calidad visual. Arrastra y suelta. Sin registros, sin límites de archivos.',
      h1: 'Compresor de PDF e Imágenes Online Gratis',
      structuredData: 'SoftwareApplication'
    }
  },

  // 4. Generador Contratos Freelance
  {
    slug: 'freelance-contract-generator',
    name: 'Generador Contratos Freelance',
    description: 'Crea contratos de servicios freelance legalmente válidos en España. Cláusulas: alcance, pagos, propiedad intelectual, confidencialidad, resolución.',
    category: 'legal',
    tags: ['contrato freelance', 'modelo contrato', 'servicios profesionales', 'autonomos'],
    tier: 'PRO',
    inputSchema: {
      type: 'object',
      properties: {
        cliente: { type: 'object', properties: { nombre: { type: 'string' }, nif: { type: 'string' }, direccion: { type: 'string' } }, required: ['nombre', 'nif'] },
        freelancer: { type: 'object', properties: { nombre: { type: 'string' }, nif: { type: 'string' }, direccion: { type: 'string' } }, required: ['nombre', 'nif'] },
        servicio: { type: 'string', description: 'Descripción del servicio' },
        honorarios: { type: 'number', description: 'Importe total (€)' },
        formaPago: { type: 'string', enum: ['unico', 'hitos', 'mensual'], default: 'hitos' },
        plazoDias: { type: 'number', default: 30 },
        propiedadIntelectual: { type: 'boolean', default: true },
        confidencialidad: { type: 'boolean', default: true }
      },
      required: ['cliente', 'freelancer', 'servicio', 'honorarios']
    },
    outputSchema: {
      type: 'object',
      properties: {
        contratoTexto: { type: 'string' },
        pdf: { type: 'string' },
        clausulas: { type: 'array', items: { type: 'string' } }
      }
    },
    testCases: [
      { input: { cliente: { nombre: 'Empresa SL', nif: 'B12345678' }, freelancer: { nombre: 'Juan Pérez', nif: '12345678Z' }, servicio: 'Desarrollo web', honorarios: 5000 }, description: 'Standard freelance contract' }
    ],
    seo: {
      targetKeywords: ['modelo contrato freelance', 'contrato servicios profesionales', 'plantilla contrato autónomo'],
      metaTitle: 'Generador Contratos Freelance España | Legal, Gratis, PDF',
      metaDescription: 'Crea contratos freelance válidos en España. Cláusulas: alcance, pagos, PI, confidencialidad. Exporta PDF/Word. Gratis para usuarios Pro.',
      h1: 'Generador de Contratos Freelance para España',
      structuredData: 'SoftwareApplication'
    }
  },

  // 5. Validador Schema.org/SEO
  {
    slug: 'schema-seo-validator',
    name: 'Validador Schema.org + SEO',
    description: 'Valida markup Schema.org, Open Graph, Twitter Cards, meta tags. Detecta errores, sugiere mejoras, exporta reporte.',
    category: 'seo',
    tags: ['schema org', 'validar seo', 'open graph', 'twitter cards', 'structured data'],
    tier: 'PRO',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'URL a validar' },
        html: { type: 'string', description: 'HTML crudo (opcional)' }
      },
      required: ['url']
    },
    outputSchema: {
      type: 'object',
      properties: {
        valid: { type: 'boolean' },
        score: { type: 'number' },
        schemaOrg: { type: 'object' },
        openGraph: { type: 'object' },
        twitterCards: { type: 'object' },
        metaTags: { type: 'object' },
        errors: { type: 'array', items: { type: 'string' } },
        warnings: { type: 'array', items: { type: 'string' } },
        suggestions: { type: 'array', items: { type: 'string' } }
      }
    },
    testCases: [
      { input: { url: 'https://example.com' }, description: 'Validate example.com' }
    ],
    seo: {
      targetKeywords: ['validador schema org', 'test structured data', 'validar open graph'],
      metaTitle: 'Validador Schema.org + SEO Gratis | Open Graph, Twitter Cards',
      metaDescription: 'Valida Schema.org, Open Graph, Twitter Cards, meta tags. Detecta errores, score SEO, sugerencias. Exporta reporte JSON/PDF.',
      h1: 'Validador de Schema.org y SEO Técnico',
      structuredData: 'SoftwareApplication'
    }
  }
];

/* ═══════════════════════════════════════════════════════════════════
   BATCH GENERATION (LoopEngine Integration)
   ═══════════════════════════════════════════════════════════════════ */

export async function batchGenerateTools(
  specs: ToolSpec[],
  creatorDid: string
): Promise<GeneratedTool[]> {
  const generator = new ToolGenerator();
  const results: GeneratedTool[] = [];
  
  for (const spec of specs) {
    try {
      const result = await generator.generateTool(spec, creatorDid);
      results.push(result);
      console.log(`✅ ${spec.slug}: ${result.deployment.success ? 'DEPLOYED' : 'FAILED'}`);
    } catch (error) {
      console.error(`❌ ${spec.slug}: ${error}`);
      results.push({
        code: '',
        files: new Map(),
        testResults: [],
        deployment: { success: false, error: String(error), logs: [] },
        caasTool: null as any
      });
    }
  }
  
  return results;
}

/* ═══════════════════════════════════════════════════════════════════
   EXPORT
   ═══════════════════════════════════════════════════════════════════ */

export const toolGenerator = new ToolGenerator();
export default toolGenerator;